import './globals.css'
import type { Metadata } from 'next'
import {ConfigProvider} from 'antd'
import LayoutProvider from '@/components/LayoutProvider'
import ReduxProvider from '@/components/ReduxProvider'
import './../stylesheets/loader.css'
export const metadata: Metadata = {
  title: 'InterCollab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en">
      <ReduxProvider>
        <LayoutProvider>
          {children}
        </LayoutProvider>
      </ReduxProvider>
    </html>
  )
}
