import './globals.css'
import type { Metadata } from 'next'
import {ConfigProvider} from 'antd'


export const metadata: Metadata = {
  title: 'InterCollab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en">
      <body>
       <ConfigProvider
        theme={{
          token:{
            colorPrimary:"#213555"
          }
        }}
      >
        {children}
       </ConfigProvider> 
      </body>
    </html>
  )
}
